### ISSUE TITLE
Misspelling in "Help to translate Taiga" page

### ISSUE THREAD

**Issue by PGNetHun** [taigaio/taiga-support#19]
There is a misspelling in Support page:
https://tree.taiga.io/support/frequently-asked-questions/can-i-use-taiga-in-my-language/#how-to-help-us-to-translate-taiga-in-your-language:

![image](https://cloud.githubusercontent.com/assets/25751703/22897532/511e2b70-f224-11e6-8743-4898f6f07b5d.png)

**Comment by bameda** [comment]
Fixed https://github.com/taigaio/taiga-support/commit/b88701f245fa43e91bb8f1cee04c65aad427a055

Thanks @PGNetHun
