### ISSUE TITLE
Support doc pages for multiple languages

### ISSUE THREAD

**Issue by filhocf** [taigaio/taiga-support#22]
Please, add support for multiples languages in Taiga Support Pages.

So, we can help in translate the interface, backend and support pages to our language (in my case, to pt-BR too).

**Comment by bameda** [comment]
There is a branch https://github.com/taigaio/taiga-support/tree/enhancement/i18n to test this. https://github.com/taigaio/taiga-support/commit/fefcd619b9e1e952032d9a7dfd1ef38c22371c83

It should be easy, you only need to create files with the name `content+{lang_code}.lr` and the web generator should do the rest.
