### ISSUE TITLE
Minor typos and grammatical erros in the docs.

### ISSUE THREAD

**Issue by nadershamma** [taigaio/taiga-support#33]
Hi 
There are some very slight errors on the [frequently-asked-questions/who-is-taiga-for](https://tree.taiga.io/support/frequently-asked-questions/who-is-taiga-for/) page.

>  We re obsessed with usability

should be;
 
> We're obsessed with usability

Next.

> to manage our own projects. But 

The word "but" should not be at the start of a sentence. 

>project management tool, or

The word "or" should not be proceeded by a comma.

May I correct these tiny errors and issue a pull request?

**Comment by migonzalvar** [comment]
Thank you, solved now in master
