### ISSUE TITLE
Please add information on running Taiga under a non-root URL

### ISSUE THREAD

**Issue by andreas-h** [taigaio/taiga-support#4]
From looking through the documentation, it looks like the installation instructions (https://taigaio.github.io/taiga-doc/dist/setup-production.html) assume that I want to install taiga under https://example.com/.

Is it possible to run taiga under a base URL of https://example.com/my/taiga/url?  If so, please add information on how to do this.  If it is not possible, please explicitly say so on the above mentioned doc.

Thanks!

**Comment by bameda** [comment]
Hi @andreas-h,  this issue is a featured related to taiga-front or taiga-doc and not about this repository, the Help and Support pages for using Taiga (final users, not sysadmins or developers).

Please could you write to the taiga mailing list? https://groups.google.com/forum/#!forum/taigaio
