### ISSUE TITLE
can't import taiga project from taiga.io to my own server

### ISSUE THREAD

**Issue by nspackaging** [taigaio/taiga-support#5]
Hi guys,

I'm installing taiga on my own server by following the how to on: http://taigaio.github.io/taiga-doc/dist/setup-production.html

I followed all the steps and at this the moment I can access taiga server on my network from another computer, I can register a new user and receive mail to confirm the registration.

The problem is when I try to import my dump file that I did export from taiga.io, I receive the following message: 
"Our Oompa Loompas are importing your project

This process could take a few minutes 
We will send you an email when ready"

I hit the accept button but the project isn't imported and I don't receive any mail.

How can I check what is the problem?

Let me show you my configuration:
TAIGA-BACK - local.py:
from .common import *

MEDIA_URL = "http://my server ip/media/"
STATIC_URL = "http://my server ip/static/"
ADMIN_MEDIA_PREFIX = "http://my server ip/static/admin/"
SITES["front"]["scheme"] = "http"
SITES["front"]["domain"] = "my server ip"

SECRET_KEY = "my secret key"

DEBUG = False
TEMPLATE_DEBUG = False
PUBLIC_REGISTER_ENABLED = True

DEFAULT_FROM_EMAIL = "no-reply@mydomain.pt"
SERVER_EMAIL = DEFAULT_FROM_EMAIL

Uncomment and populate with proper connection parameters

for enable email sending. EMAIL_HOST_USER should end by @domain.tld

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_USE_TLS = False
EMAIL_HOST = "my smtp server"
# EMAIL_HOST_USER = ""
# EMAIL_HOST_PASSWORD = ""

EMAIL_PORT = 25

Uncomment and populate with proper connection parameters

for enable github login/singin.
# GITHUB_API_CLIENT_ID = "yourgithubclientid"
# GITHUB_API_CLIENT_SECRET = "yourgithubclientsecret"

from .celery import *

BROKER_URL = 'amqp://guest:guest@localhost:5672//'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ENABLED = True

EVENTS_PUSH_BACKEND = "taiga.events.backends.rabbitmq.EventsPushBackend"
EVENTS_PUSH_BACKEND_OPTIONS = {"url": "amqp://taiga:PASSWORD@localhost:5672/taiga"}

TAIGA-FRONT - conf.json:

{
"api": "http://my server ip:8001/api/v1/",
"eventsUrl": "ws://my server ip/events",
"debug": "true",
"publicRegisterEnabled": true,
"feedbackEnabled": true,
"privacyPolicyUrl": null,
"termsOfServiceUrl": null,
"maxUploadFileSize": null,
"contribPlugins": []
}

NGINX - /etc/nginx/sites-available/taiga:
server {
listen 80 default_server;
server_name _;

large_client_header_buffers 4 32k;
client_max_body_size 100M;
charset utf-8;

access_log /home/my user/logs/nginx.access.log;
error_log /home/my user/logs/nginx.error.log;
# Frontend

location / {
    root /home/my user/taiga-front-dist/dist/;
    try_files $uri $uri/ /index.html;
}
# Backend

location /api {
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Scheme $scheme;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass http://127.0.0.1:8001/api;
    proxy_redirect off;
}
# Django admin access (/admin/)

location /admin {
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Scheme $scheme;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass http://127.0.0.1:8001$request_uri;
    proxy_redirect off;
}
# Static files

location /static {
    alias /home/my user/taiga-back/static;
}
# Media files

location /media {
    alias /home/my user/taiga-back/media;
}
}

I hope you can help me. I really need to have taiga ready to work on a production environment in my company.

Best Regards

**Comment by bameda** [comment]
Hi @nspackaging this issue is related to a problem with your instalation project and not about this repository, the Help and Support pages for using Taiga (final users, not sysadmins or developers).

Please could you write to the taiga mailing list? https://groups.google.com/forum/#!forum/taigaio

Thanks
